# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_auto_20171031_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
    ]
