# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('antenatal_history', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration_of_pregnancy', models.FloatField(blank=True, null=True)),
                ('mode_of_delivery', models.CharField(blank=True, max_length=128, null=True)),
                ('hospital', models.CharField(blank=True, max_length=128, null=True)),
                ('doctor', models.CharField(blank=True, max_length=128, null=True)),
                ('father_abo', models.CharField(blank=True, max_length=3, null=True)),
                ('mother_abo', models.CharField(blank=True, max_length=3, null=True)),
                ('consanguinity', models.CharField(blank=True, max_length=128, null=True)),
                ('order', models.CharField(blank=True, max_length=128, null=True)),
                ('diseases', models.CharField(blank=True, max_length=512, null=True)),
                ('nutrition', models.CharField(blank=True, max_length=1024, null=True)),
                ('bcg', models.BooleanField(default=False)),
                ('topv_0', models.BooleanField(default=False)),
                ('topv_2m', models.BooleanField(default=False)),
                ('topv_4m', models.BooleanField(default=False)),
                ('topv_6m', models.BooleanField(default=False)),
                ('topv_9m', models.BooleanField(default=False)),
                ('topv_1y', models.BooleanField(default=False)),
                ('dpt_2m', models.BooleanField(default=False)),
                ('dpt_4m', models.BooleanField(default=False)),
                ('dpt_6m', models.BooleanField(default=False)),
                ('hbv_0', models.BooleanField(default=False)),
                ('hbv_2m', models.BooleanField(default=False)),
                ('hbv_4m', models.BooleanField(default=False)),
                ('hbv_6m', models.BooleanField(default=False)),
                ('mmr_12m', models.BooleanField(default=False)),
                ('mmr_18m', models.BooleanField(default=False)),
                ('other_0', models.BooleanField(default=False)),
                ('other_1', models.BooleanField(default=False)),
                ('social_smile', models.IntegerField(blank=True, null=True)),
                ('head_support', models.IntegerField(blank=True, null=True)),
                ('set_alone', models.IntegerField(blank=True, null=True)),
                ('start_teething', models.IntegerField(blank=True, null=True)),
                ('crawl', models.IntegerField(blank=True, null=True)),
                ('walk_alone', models.IntegerField(blank=True, null=True)),
                ('speech', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField()),
                ('problem', models.CharField(max_length=1024)),
                ('h_c', models.FloatField()),
                ('l_t', models.FloatField()),
                ('medications', models.CharField(max_length=1024)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Patient')),
            ],
        ),
    ]
