# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20171210_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
