# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0007_instance_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='reseller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reseller', to=settings.AUTH_USER_MODEL),
        ),
    ]
