# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_instance_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
