# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_instance_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reseller', to=settings.AUTH_USER_MODEL),
        ),
    ]
