# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_auto_20180116_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='payments',
            field=models.IntegerField(default=0),
        ),
    ]
