# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_instance_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='trials',
            field=models.IntegerField(default=1),
        ),
    ]
