# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_auto_20180116_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reseller', to=settings.AUTH_USER_MODEL),
        ),
    ]
