# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='task_type',
            field=models.IntegerField(choices=[('1', '\u0643\u0634\u0641 \u062c\u062f\u064a\u062f'), ('2', '\u0625\u0639\u0627\u062f\u0629 \u0643\u0634\u0641')], verbose_name='Type'),
        ),
    ]
