# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0003_auto_20171109_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='paid',
            field=models.FloatField(default=0.0),
        ),
    ]
