# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0004_queue_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
