# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0006_auto_20171124_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='attend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
