# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0008_queue_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='attend',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='patient',
        ),
    ]
