# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0009_auto_20171124_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='refund_reason',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
