# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0011_queue_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
