# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0014_auto_20171210_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
