# Generated by Django 2.0.2 on 2018-02-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_auto_20180204_0105'),
        ('Queues', '0017_clinic_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0)),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.Instance')),
            ],
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['id']},
        ),
    ]
