# Generated by Django 2.0.2 on 2018-02-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0018_auto_20180213_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='task_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Queues.ClinicServices', verbose_name='Service'),
        ),
    ]
