# Generated by Django 2.0.2 on 2018-02-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0019_auto_20180213_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='service_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
