# Generated by Django 2.0.2 on 2018-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queues', '0021_queue_balance_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='balance_before',
            field=models.FloatField(default=0.0, verbose_name='Old Balance'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='paid',
            field=models.FloatField(default=0.0, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='service_cost',
            field=models.FloatField(default=0.0, verbose_name='Service Cost'),
        ),
    ]
