# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20171210_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransaction',
            name='comment',
            field=models.TextField(verbose_name='\u0645\u0644\u0627\u062d\u0638\u0627\u062a'),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='moneytransaction',
            name='outcome',
            field=models.FloatField(default=0, verbose_name='\u0645\u0635\u0631\u0648\u0641'),
        ),
    ]
