# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20171211_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetransaction',
            options={'ordering': ('-id',)},
        ),
    ]
