# Generated by Django 2.0.2 on 2018-02-15 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Records', '0020_auto_20180214_1611'),
        ('Queues', '0022_auto_20180215_1409'),
        ('Accounts', '0004_auto_20171211_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('credit', models.FloatField(default=0.0)),
                ('debit', models.FloatField(default=0.0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Records.Patient')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Queues.ClinicServices')),
            ],
        ),
    ]
