# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resellers', '0002_customertransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellertransaction',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='resellertransaction',
            name='debit',
        ),
        migrations.AddField(
            model_name='resellertransaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
