# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resellers', '0003_auto_20180116_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='done_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resellertransaction',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resellers.Service', verbose_name=b'Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_giga',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='resellertransaction',
            name='amount',
            field=models.FloatField(default=0, verbose_name=b'Amount'),
        ),
        migrations.AlterField(
            model_name='resellertransaction',
            name='comment',
            field=models.TextField(null=True, verbose_name=b'Comment'),
        ),
        migrations.AlterField(
            model_name='resellertransaction',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.Instance', verbose_name=b'Doctor'),
        ),
        migrations.AlterField(
            model_name='resellertransaction',
            name='reseller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
