# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resellers', '0004_auto_20180116_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='extra_giga',
            new_name='extra_gigabytes',
        ),
    ]
