# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resellers', '0007_auto_20180116_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellertransaction',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='resellertransaction',
            name='service',
        ),
        migrations.AddField(
            model_name='resellertransaction',
            name='customer_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resellers.CustomerTransaction'),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resellertransaction',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name=b'Comment'),
        ),
    ]
