# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resellers', '0008_auto_20180116_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseller',
            old_name='discount_percentage',
            new_name='percentage_on_first',
        ),
        migrations.AddField(
            model_name='reseller',
            name='percentage_on_renewal',
            field=models.FloatField(default=0.0),
        ),
    ]
