# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resellers', '0009_auto_20180116_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertransaction',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='resellertransaction',
            options={'ordering': ['-id']},
        ),
    ]
