# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resellers', '0010_auto_20180116_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellertransaction',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='resellertransaction',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
