# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bcg',
            new_name='abortion',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dpt_2m',
            new_name='ectopic',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='birthday',
            new_name='husband_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dpt_4m',
            new_name='v_mole',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='crawl',
            new_name='xx',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='head_support',
            new_name='xy',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='problem',
            new_name='comments_complain',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='l_t',
            new_name='fundel_level',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='age',
            new_name='urine_suger',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antenatal_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consanguinity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dpt_6m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='duration_of_pregnancy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='father_abo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hbv_0',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hbv_2m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hbv_4m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hbv_6m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mmr_12m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mmr_18m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mode_of_delivery',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mother_abo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='order',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='other_0',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='other_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='set_alone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='social_smile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='start_teething',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='topv_0',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='topv_1y',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='topv_2m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='topv_4m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='topv_6m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='topv_9m',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='walk_alone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wt_at_birth',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='h_c',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='medications',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cbc',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cfm',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='co',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deliveries',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='drugs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='e2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='e_d_d',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fsh',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hb',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='HB%'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hs',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypertention',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='l_n_m_b',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lh',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lt_ov',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lt_tube',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='male_f',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='operations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_hermones',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_investigation',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_laprospic_finding',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rh',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rt_ov',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rt_tube',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rubella',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='still_birth',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taxoplasma',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tsh',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='twins',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ut',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='b_p',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='B/P'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='h_b_percent',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='HB%'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='oedama',
            field=models.FloatField(blank=True, null=True, verbose_name='Oedama'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='prescription',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='urine_albumin',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Med.'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='week',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
