# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_auto_20171206_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cancer',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cns',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
