# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0003_auto_20171206_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='husband_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
