# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0004_auto_20171210_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='prescription',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='prescription',
            field=models.ManyToManyField(to='Records.Medicine'),
        ),
    ]
