# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20171210_1220'),
        ('Records', '0005_auto_20171210_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Instance'),
        ),
    ]
