# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Records', '0006_patient_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
