# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0008_auto_20171210_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='prescription',
            field=models.ManyToManyField(blank=True, to='Records.Medicine'),
        ),
    ]
