# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0010_auto_20171217_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='co',
        ),
        migrations.AddField(
            model_name='patient',
            name='co',
            field=models.ManyToManyField(blank=True, to='Records.Complain'),
        ),
    ]
