# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0012_complain_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antenatal_history',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bcg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consanguinity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='crawl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dpt_2m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='dpt_4m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='dpt_6m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='duration_of_pregnancy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_abo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hbv_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hbv_2m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hbv_4m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hbv_6m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='head_support',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mmr_12m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='mmr_18m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='mode_of_delivery',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_abo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nutrition',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='order',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='set_alone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_smile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='speech',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='start_teething',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='topv_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='topv_1y',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='topv_2m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='topv_4m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='topv_6m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='topv_9m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='walk_alone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='wt_at_birth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='age',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='h_c',
            field=models.FloatField(blank=True, null=True, verbose_name='H.C'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='l_t',
            field=models.FloatField(blank=True, null=True, verbose_name='Lt.'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='problem',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
