# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0013_auto_20180114_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='laprospic_report',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
