# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0014_patient_laprospic_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
