# Generated by Django 2.0.2 on 2018-02-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0018_auto_20180214_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlabtest',
            old_name='patient',
            new_name='record',
        ),
    ]
